/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.stream.JsonReader;
import org.junit.Before;
import org.junit.Test;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void testQuoteHasAnAuthor() throws FileNotFoundException {
        String filePath = "src/main/resources/quotes.json";
        Quote[] quotes = App.returnQuotes(filePath);
        String randomQuote = App.getRandomQuote(quotes).toString();
        assertTrue(randomQuote.contains("Author"));
    }
    @Test
    public void testLengthOfReturnedArray() throws FileNotFoundException {
        String filePath = "src/main/resources/quotes.json";
        Gson gson = new Gson();
        JsonReader reader = new JsonReader(new FileReader(filePath));
        Quote[] quotes = gson.fromJson(reader, Quote[].class);
        assertEquals(138,quotes.length);
    }
    @Test
    public void testQuoteHasText() throws FileNotFoundException {
        String filePath = "src/main/resources/quotes.json";
        Quote[] quotes = App.returnQuotes(filePath);
        String randomQuote = App.getRandomQuote(quotes).toString();
        assertTrue(randomQuote.contains("Quote"));

    }
    @Test
    public void testRandomNumberGenerator() throws FileNotFoundException {
        String filePath = "src/main/resources/quotes.json";
        Gson gson = new Gson();
        JsonReader reader = new JsonReader(new FileReader(filePath));
        Quote[] quotes = gson.fromJson(reader, Quote[].class);
        int newRandom = (int) (Math.random() * quotes.length);
        int high = quotes.length - 1;
        int low = 0;
        assertTrue("Error, random is too high", high >= newRandom);
        assertTrue("Error, random is too low",  low  <= newRandom);

    }

    @Test
    public void testgetQuoteFromInternet() throws IOException {
        String randomQuote = App.getQuotes();
        assertTrue(randomQuote.contains("From internet "));

    }
    @Test
    public void testgetQuoteFromFile() throws IOException {
        //turn wi-fi off before trying
        String randomQuote = App.getQuotes();
        assertTrue(randomQuote.contains("From file "));

    }
    @Test
    public void testWriteToFile() throws IOException {
        String filePath = "src/main/resources/quotes.json";
        Quote[] quotes = App.returnQuotes(filePath);
        int numberOfQuotes = quotes.length;
        Quote[] quotesNew = App.returnQuotes(filePath);
        int currentNumberOfQuotes = quotesNew.length;
        int curr = numberOfQuotes;
        assertEquals("New number of tags", currentNumberOfQuotes, curr);

    }
}
