/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.stream.JsonReader;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;

public class App {
    public static void main(String[] args) throws FileNotFoundException {
       String newQuote = returnQuote("src/main/resources/quotes.json");
       System.out.println(newQuote);
    }

    public static String returnQuote(String filePath) throws FileNotFoundException {
        Gson gson = new Gson();
        JsonReader reader = new JsonReader(new FileReader(filePath));
        Quote[] quotes = gson.fromJson(reader, Quote[].class);
        int newRandom = (int) (Math.random() * quotes.length);
        return quotes[newRandom].toString();
    }

    public static void main (String[] args){
        public class QuotesApi {

            try {
                // https://www.baeldung.com/java-http-request
                URL url = new URL("http://swquotesapi.digitaljedi.dk/index.html");
                HttpURLConnection connection = (HttpURLConnection) url.openConnection();
                connection.setRequestMethod("GET");
                System.out.println(connection.getResponseCode());

                // synchronous: java is going to be working on running line 15 for a while
                BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
                String inputLine;
                StringBuilder content = new StringBuilder();
                while ((inputLine = in.readLine()) != null) {
                    content.append(inputLine);
                }
                in.close();

                System.out.println(content);
            } catch (
            IOException e) {
                e.printStackTrace();
            }
        }
    }

    }
}
